### ISSUE TITLE
react-native-internal-notification not working

### ISSUE THREAD

**Issue by JoaoVitorChaves-05** [VeXell/react-native-internal-notification#2]
Hello, i am not able to use the library, apparently everything is fine, but notification does not work.
This is my component:
![image](https://user-images.githubusercontent.com/80546427/137595487-b0a53f00-cb77-4a14-8abc-4218a7e5786c.png)

And this my NotificationProvider:
![image](https://user-images.githubusercontent.com/80546427/137595462-d453397a-b5f0-4978-952c-f9bcdf1985a0.png)

I imported everything correctly, I didn't get any errors, it just didn't work.

**Comment by VeXell** [comment]
@JoaoVitorChaves-05 You should wrap your root App with `NotificationProvider` from library and also check might be you have negative margins on top.

**Comment by JoaoVitorChaves-05** [comment]
> @JoaoVitorChaves-05 You should wrap your root App with `NotificationProvider` from library and also check might be you have negative margins on top.

My styles from App:
![image](https://user-images.githubusercontent.com/80546427/137595606-ac89d03e-3675-4887-8113-1f8019a43f31.png)

My styles from component:
![image](https://user-images.githubusercontent.com/80546427/137595623-ce121611-cbf0-41a8-9798-17ba62a26f1a.png)

**Comment by VeXell** [comment]
@JoaoVitorChaves-05 Do you see "notification" in console? Might be would be better to add some console.log commands in my library in `node_modules` to check if code is working correct.

**Comment by JoaoVitorChaves-05** [comment]
> @JoaoVitorChaves-05 Do you see "notification" in console? Might be would be better to add some console.log commands in my library in `node_modules` to check if code is working correct.

Yes, I see "notification" in console.

**Comment by VeXell** [comment]
@JoaoVitorChaves-05 Have a look on my example with expo https://expo.dev/@vexell/test-notification. And git repo: https://github.com/VeXell/expo-notifications . It works fine. Might be you have some problems with navigation, but i use the same component in my project and it works.

**Comment by VeXell** [comment]
@JoaoVitorChaves-05 you right. something wrong with Android only. It works on ios. I will fix it

**Comment by VeXell** [comment]
@JoaoVitorChaves-05 Should be fixed in 1.0.7. Thank you. (please confirm on your device)

**Comment by JoaoVitorChaves-05** [comment]
@VeXell Thank you for your help
